version: '3'

services:
  mlflow:
    image: mlflow
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db

  prediction_service:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./models:/app/models
    depends_on:
      - mlflow